# -*- coding: utf-8 -*-
"""Chest X-Ray Disease Detection using CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKzLel4mU0ck_9YPRNKmDgePr_JOj45x
"""

tf.keras.utils.set_random_seed(42)

import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import pathlib as pl

print("TF VERSION :",tf.__version__)
print("GPU Avalable:", tf.config.list_physical_devices('GPU'))

import kagglehub
dataset_path = kagglehub.dataset_download("paultimothymooney/chest-xray-pneumonia")

data_dir = pl.Path(dataset_path) / 'chest_xray'

for split in ["train","val","test"]:
  normal = len(list((data_dir/split/"NORMAL").glob("*.jpeg")))
  pneumonia = len(list((data_dir/split/"PNEUMONIA").glob("*.jpeg")))
  print(f"{split}: NORMAL={normal}, PNEUMONIA={pneumonia}")

fig , axes = plt.subplots(2,4, figsize=(16,8))
for i , cls in enumerate(["NORMAL","PNEUMONIA"]):
  files = list((data_dir/"train"/cls).glob("*.jpeg"))[:4]
  for j, f in enumerate(files):
    img = plt.imread(f)
    axes[i,j].imshow(img, cmap="gray")
    axes[i,j].set_title(cls)
    axes[i,j].axis("off")
plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split
import shutil
all_files = []
all_labels = []
for cls in ["NORMAL", "PNEUMONIA"]:
    for split in ["train", "val"]:
        files = list((data_dir/split/cls).glob("*.jpeg"))
        all_files.extend(files)
        all_labels.extend([cls]*len(files))

train_files, val_files, train_labels, val_labels = train_test_split(
    all_files, all_labels, test_size=0.15, stratify=all_labels, random_state=42
)

print(f"New train: {len(train_files)} | New val: {len(val_files)}")
new_base = pl.Path("/content/data_clean")
for split, files, labels in [("train", train_files, train_labels), ("val", val_files, val_labels)]:
    for f, l in zip(files, labels):
        dest = new_base/split/l
        dest.mkdir(parents=True, exist_ok=True)
        shutil.copy(f, dest/f.name)
shutil.copytree(data_dir/"test", new_base/"test")

from sklearn.utils.class_weight import compute_class_weight

classes = np.array([0, 1])
labels_numeric = [0 if l == "NORMAL" else 1 for l in train_labels]

weights = compute_class_weight(class_weight="balanced", classes=classes, y=labels_numeric)
class_weight_dict = {0: weights[0], 1: weights[1]}
print("Class weights:", class_weight_dict)

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    new_base/"train",
    labels="inferred",
    label_mode="binary",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True,
    seed=42
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    new_base/"val",
    labels="inferred",
    label_mode="binary",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    new_base/"test",
    labels="inferred",
    label_mode="binary",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print("Class names:", train_ds.class_names)

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.05),
    tf.keras.layers.RandomZoom(0.1),
    tf.keras.layers.RandomContrast(0.1),
])

normalization_layer = tf.keras.layers.Rescaling(1./255)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)
test_ds = test_ds.cache().prefetch(buffer_size=AUTOTUNE)

def build_baseline_cnn():
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(224, 224, 3)),
        data_augmentation,
        normalization_layer,

        tf.keras.layers.Conv2D(32, 3, activation="relu", padding="same"),
        tf.keras.layers.MaxPooling2D(),

        tf.keras.layers.Conv2D(64, 3, activation="relu", padding="same"),
        tf.keras.layers.MaxPooling2D(),

        tf.keras.layers.Conv2D(128, 3, activation="relu", padding="same"),
        tf.keras.layers.MaxPooling2D(),

        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dropout(0.3),
        tf.keras.layers.Dense(1, activation="sigmoid")
    ])
    return model

baseline_model = build_baseline_cnn()

baseline_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy", tf.keras.metrics.Precision(name="precision"),
             tf.keras.metrics.Recall(name="recall")]
)

baseline_model.summary()

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=3, restore_best_weights=True
)

history_baseline = baseline_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    class_weight=class_weight_dict,
    callbacks=[early_stop]
)

def build_transfer_model(base_trainable=False):
    base_model = tf.keras.applications.DenseNet121(
        weights="imagenet",
        include_top=False,
        input_shape=(224, 224, 3)
    )
    base_model.trainable = base_trainable

    inputs = tf.keras.layers.Input(shape=(224, 224, 3))
    x = data_augmentation(inputs)
    x = tf.keras.applications.densenet.preprocess_input(x)
    x = base_model(x, training=False)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dense(128, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.4)(x)
    outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)

    model = tf.keras.Model(inputs, outputs)
    return model, base_model

transfer_model, base_model = build_transfer_model(base_trainable=False)

transfer_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy", tf.keras.metrics.Precision(name="precision"),
             tf.keras.metrics.Recall(name="recall")]
)

transfer_model.summary()

early_stop_transfer = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=3, restore_best_weights=True
)

history_transfer_phase1 = transfer_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    class_weight=class_weight_dict,
    callbacks=[early_stop_transfer]
)

base_model.trainable = True

fine_tune_at = 300

for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

# Recompile with a MUCH lower learning rate
transfer_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),  # 100x smaller than before
    loss="binary_crossentropy",
    metrics=["accuracy", tf.keras.metrics.Precision(name="precision"),
             tf.keras.metrics.Recall(name="recall")]
)

print(f"Trainable layers: {sum(l.trainable for l in base_model.layers)}")

early_stop_finetune = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=3, restore_best_weights=True
)

history_finetune = transfer_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    class_weight=class_weight_dict,
    callbacks=[early_stop_finetune]
)

transfer_model, base_model = build_transfer_model(base_trainable=False)

transfer_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy", tf.keras.metrics.Precision(name="precision"),
             tf.keras.metrics.Recall(name="recall")]
)

checkpoint_phase1 = tf.keras.callbacks.ModelCheckpoint(
    "phase1_best.keras", monitor="val_loss", save_best_only=True
)
early_stop_phase1 = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=3, restore_best_weights=True
)

history_phase1_v2 = transfer_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    class_weight=class_weight_dict,
    callbacks=[checkpoint_phase1, early_stop_phase1]
)

base_model.trainable = True

fine_tune_at = 400
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

print(f"Trainable layers this time: {sum(l.trainable for l in base_model.layers)}")

transfer_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="binary_crossentropy",
    metrics=["accuracy", tf.keras.metrics.Precision(name="precision"),
             tf.keras.metrics.Recall(name="recall")]
)

checkpoint_phase2 = tf.keras.callbacks.ModelCheckpoint(
    "phase2_best.keras", monitor="val_loss", save_best_only=True
)
early_stop_phase2 = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=3, restore_best_weights=True
)

history_phase2_v2 = transfer_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    class_weight=class_weight_dict,
    callbacks=[checkpoint_phase2, early_stop_phase2]
)

phase1_model = tf.keras.models.load_model("phase1_best.keras")
phase2_model = tf.keras.models.load_model("phase2_best.keras")

print("=== Phase 1 (Frozen DenseNet121) — TEST SET ===")
phase1_results = phase1_model.evaluate(test_ds, return_dict=True)
print(phase1_results)

print("\n=== Phase 2 (Fine-tuned, 27 layers) — TEST SET ===")
phase2_results = phase2_model.evaluate(test_ds, return_dict=True)
print(phase2_results)

from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc


y_true = np.concatenate([y.numpy() for x, y in test_ds], axis=0).flatten()

y_prob_phase1 = phase1_model.predict(test_ds).flatten()
y_prob_phase2 = phase2_model.predict(test_ds).flatten()


for threshold in [0.5, 0.4, 0.3, 0.2, 0.1]:
    y_pred = (y_prob_phase2 >= threshold).astype(int)
    report = classification_report(y_true, y_pred, target_names=["NORMAL", "PNEUMONIA"], output_dict=True)
    print(f"Threshold {threshold}: recall={report['PNEUMONIA']['recall']:.4f}, "
          f"precision={report['PNEUMONIA']['precision']:.4f}, "
          f"accuracy={report['accuracy']:.4f}")

best_threshold = 0.4
y_pred_final = (y_prob_phase2 >= best_threshold).astype(int)

print(classification_report(y_true, y_pred_final, target_names=["NORMAL", "PNEUMONIA"]))

cm = confusion_matrix(y_true, y_pred_final)
plt.figure(figsize=(6,5))
plt.imshow(cm, cmap="Blues")
plt.colorbar()
plt.xticks([0,1], ["NORMAL", "PNEUMONIA"])
plt.yticks([0,1], ["NORMAL", "PNEUMONIA"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
for i in range(2):
    for j in range(2):
        plt.text(j, i, cm[i,j], ha="center", va="center", color="black", fontsize=14)
plt.title(f"Confusion Matrix (Phase 2, threshold={best_threshold})")
plt.show()

phase2_model.save("final_model.keras")

def make_gradcam_heatmap(img_array, model, last_conv_layer_name="conv5_block16_2_conv"):
    grad_model = tf.keras.models.Model(
        model.inputs,
        [model.get_layer(last_conv_layer_name).output if hasattr(model.get_layer(last_conv_layer_name), 'output') else None, model.output]
    )
    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        loss = predictions[:, 0]

    grads = tape.gradient(loss, conv_outputs)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]
    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap)
    return heatmap.numpy()

for layer in base_model.layers[-5:]:
    print(layer.name, layer.output.shape if hasattr(layer, 'output') else None)

def make_gradcam_heatmap(img_array, full_model, last_conv_layer_name=None):
    x = tf.keras.applications.densenet.preprocess_input(img_array)

    # 1. Find the correct base model by checking for a large number of layers
    base_model_index = None
    base_model = None
    for i, layer in enumerate(full_model.layers):
        if isinstance(layer, tf.keras.Model) and len(layer.layers) > 10:
            base_model = layer
            base_model_index = i
            break

    if base_model is None:
        raise ValueError("Could not find the pre-trained base model inside full_model.layers")

    # 2. Safely auto-detect the last convolutional or concatenation layer
    if last_conv_layer_name is None:
        for layer in reversed(base_model.layers):
            # Check by layer class name string or layer name string
            layer_type = layer.__class__.__name__.lower()
            if "conv" in layer_type or "conv" in layer.name or "concat" in layer.name:
                last_conv_layer_name = layer.name
                print(f"Automatically selected target layer: {last_conv_layer_name}")
                break

        if last_conv_layer_name is None:
            raise ValueError("Could not automatically find a convolutional layer. Please specify last_conv_layer_name.")

    conv_layer_model = tf.keras.Model(base_model.input, base_model.get_layer(last_conv_layer_name).output)
    head_layers = full_model.layers[base_model_index + 1:]

    with tf.GradientTape() as tape:
        conv_output = conv_layer_model(x)
        tape.watch(conv_output)
        y = conv_output
        for layer in head_layers:
            y = layer(y)
        loss = y[:, 0]

    grads = tape.gradient(loss, conv_output)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    conv_output = conv_output[0]
    heatmap = conv_output @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0) / (tf.math.reduce_max(heatmap) + 1e-8)
    return heatmap.numpy()

import inspect
print(inspect.signature(make_gradcam_heatmap))

import cv2

def display_gradcam(img_path, heatmap, alpha=0.4):
    img = tf.keras.utils.load_img(img_path, target_size=(224, 224))
    img = tf.keras.utils.img_to_array(img)

    heatmap_resized = cv2.resize(heatmap, (224, 224))
    heatmap_resized = np.uint8(255 * heatmap_resized)
    heatmap_colored = cv2.applyColorMap(heatmap_resized, cv2.COLORMAP_JET)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)

    superimposed = heatmap_colored * alpha + img
    superimposed = np.uint8(superimposed)
    return img.astype("uint8"), superimposed

# Test on a few PNEUMONIA test images
pneumonia_files = list((new_base/"test"/"PNEUMONIA").glob("*.jpeg"))[:3]

fig, axes = plt.subplots(2, 3, figsize=(15, 10))
for i, img_path in enumerate(pneumonia_files):
    img = tf.keras.utils.load_img(img_path, target_size=(224, 224))
    img_array = tf.keras.utils.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)  # add batch dimension

    heatmap = make_gradcam_heatmap(img_array, phase2_model)
    original, overlay = display_gradcam(img_path, heatmap)

    prob = phase2_model.predict(img_array, verbose=0)[0][0]

    axes[0, i].imshow(original.astype("uint8"))
    axes[0, i].set_title(f"Original (Pred: {prob:.2f})")
    axes[0, i].axis("off")

    axes[1, i].imshow(overlay)
    axes[1, i].set_title("Grad-CAM Overlay")
    axes[1, i].axis("off")

plt.tight_layout()
plt.show()

normal_files = list((new_base/"test"/"NORMAL").glob("*.jpeg"))[:3]

fig, axes = plt.subplots(2, 3, figsize=(15, 10))
for i, img_path in enumerate(normal_files):
    img = tf.keras.utils.load_img(img_path, target_size=(224, 224))
    img_array = tf.keras.utils.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)

    heatmap = make_gradcam_heatmap(img_array, phase2_model)
    original, overlay = display_gradcam(img_path, heatmap)

    prob = phase2_model.predict(img_array, verbose=0)[0][0]

    axes[0, i].imshow(original.astype("uint8"))
    axes[0, i].set_title(f"Original NORMAL (Pred: {prob:.2f})")
    axes[0, i].axis("off")

    axes[1, i].imshow(overlay)
    axes[1, i].set_title("Grad-CAM Overlay")
    axes[1, i].axis("off")

plt.tight_layout()
plt.show()

